export enum ErrorMsg {
  /** 权限状态码 **/
  INVALID_IDENTITY_INFORMATION = '无效的用户信息',
  PERMISSION_DENIED = '权限不足',
  /** auth状态码 */
  TOKEN_INVALID = 'TOKEN INVALID',
  YOU_DO_NOT_OWN_THIS_RESOURCE = 'YOU DO NOT OWN THIS RESOURCE',
  VERIFICATION_CODE_ERROR = 'VERIFICATION ERROR',
  VERIFICATION_CODE_SEND_FAILED = 'VERIFICATION CODE SEND ERROR',
  /** 用户状态码 **/
  UNKNOWN_ERROR = 'UNKNOWN ERROR', //未知错误
  USER_ID_INVALID = 'USER ID INVALID', //用户id无效
  USER_NOT_EXIST = 'USER NOT EXIST', // 用户不存在
  USER_EXIST = 'USER EXIST',
  EMAIL_EXIST = 'EMAIL EXIST',
  AVATAR_UNSUPPORTED_FILE_TYPE = 'AVATAR UNSUPPORTED FILE TYPE',
}
